export const OFFER_EXAMPLE = {
  id: '5e57828f1861f6001122d4bf',
  newId: '5e57828f1861f6001122d4bf',
  name: 'Наличными под залог недвижимости',
  category: 'Credit',
  security: {
    pledgeList: ['existing-property'],
    guarantor: false,
  },
  obtainingMethod: ['card'],
  customerRequirements: {
    age: 18,
    lastExperience: 0,
    fullExperience: 0,
    manAgeAtRepayment: 70,
    femaleAgeAtRepayment: 70,
    salary: 0,
    demands: ['rf-citizenship', 'permanent-registration', 'temporary-registration', 'fixed-income'],
    type: 'default',
    documents: [['2'], ['29']],
    conditions: '',
    description: '',
    solvencyProof: [
      {
        amount: {
          from: 200000,
          to: 15000000,
        },
        list: [],
      },
    ],
  },
  insurances: [
    {
      required: false,
      isFinalRate: false,
      rate: 0.5,
      description: 'Ставка выше: на 0.5% при залоге квартиры, апартаментов; на 2% при залоге иной недвижимости.',
    },
  ],
  totalAmount: {
    from: 200000,
    to: 15000000,
  },
  totalTerm: {
    from: 'P3M',
    to: 'P15Y',
  },
  organization: {
    id: '645',
    newId: '5bb4f769245bc22a520a6353',
    alias: 't-bank',
    license: '2673',
    logo: 'https://s37498.cos.ngenix.net/organizations/logotypes/web/5bb4f769245bc22a520a6353.svg?v=0.ce',
    roundLogo: 'https://s91588.cdn.ngenix.net/organizations/logotypes/android/5bb4f769245bc22a520a6353.svg',
    name: 'Т-банк',
    website: 'https://www.tbank.ru/',
    personalAccountSite: 'https://www.tinkoff.ru/login/',
    personalAccountAppLink: '',
    personalAccountName: 'Тинькофф',
    phones: ['8 800 555-77-78'],
    ratings: {
      sravniRuRating: 4.9,
    },
    audience: 0,
  },
  advertising: {
    id: '62f37fd9545ac20023e64951',
    actualCost: 300,
    cost: 500,
    button: {
      color: 'green',
      text: 'Отправить заявку',
    },
    monetization: {
      kind: 'request-long',
      finalDecision: false,
      selectedScoringModels: ['gen7'],
      scoring: {
        nbki: {},
        okb: {
          from: 680,
          to: 1250,
        },
        gen7: {},
      },
      pixels: {
        click:
          'https://goto.startracking.ru/api/v1/redirect?aff_id=2&aff_sub3=ip_source%3Dnone%7Cip_category%3Dcredit%7Cip_campaign%3Dnone%7Cip_sub1%3Dtinkoff-bank%7Cip_sub2%3Dnalichnymi-pod-zalog-kvartiry&offer_id=1623',
        display: 'https://goto.startracking.ru/api/v1/impression?offer_id=1623&aff_id=2',
      },
    },
    position: 7,
    priority: false,
    priorityInGroup: false,
    paidBank: false,
    isMarketplace: false,
    isLastMile: false,
    callCenterPriority: false,
    isFinalOffer: false,
    hasExactConditions: false,
    positionOnLanding: 1,
    superPositionManual: null,
  },
  calculatedValues: {
    rate: {
      from: 14.9,
      to: 40,
    },
    isDailyRate: false,
    amount: 220000,
    overpayment: 54162,
    perMonth: 7616,
    term: 'P3Y',
    termInMonths: 36,
  },
  productGroup: 'credit',
  applicationSent: false,
  matchingLocations: [
    {
      route: '6.83.',
      routeGar: '1405113',
      garId: 1405113,
      fias: '0c5b2444-70a0-4932-980c-b4dc0d3f02b5',
      name: 'Москва',
      lat: 55.7540471,
      lon: 37.620405,
    },
  ],
  additionalSmsValidation: false,
  restrictionFlags: [],
  preApprovalStatus: null,
  loansStatus: null,
};
